### ISSUE TITLE
RGB Platforms dont work

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [MaxNiftyNine/Universal-Lemonloader-VR-Mods#1]
The RGB platforms did not work in Robot Tag
[Latest.log](https://github.com/MaxNiftyNine/Universal-Lemonloader-VR-Mods/files/13326855/Latest.log)

**Comment by MaxNiftyNine** [comment]
RGB Platforms requires game to support easy inputs, which robot tag doesn't, you need to make your own mod for a non easy inputs mod
